// AUTO-GENERATED by scripts/generate-approved.mjs — do not edit
// Source: data/store.json (committed by backend via GitHub API)
import type { Wine } from "./types";

export const approvedWines: Wine[] = [];
